version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quero2paytest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5449:5432"